// Board
export const REQUEST_BOARDS = 'REQUEST_BOARDS';
export const RECEIVE_BOARDS = 'RECEIVE_BOARDS';
export const CREATE_BOARD = 'CREATE_BOARD';
export const SELECT_BOARD = 'SELECT_BOARD';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';
export const JOIN_BOARD = 'JOIN_BOARD';
export const LEAVE_BOARD = 'LEAVE_BOARD';
export const UPDATE_VIEW = 'UPDATE_VIEW';
export const BEGIN_SELECTION = 'BEGIN_SELECTION';
export const END_SELECTION = 'END_SELECTION';
export const REQUEST_GROUPS = 'REQUEST_GROUPS';
export const RECEIVE_GROUPS = 'RECEIVE_GROUPS';
export const CREATE_GROUP = 'CREATE_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const REQUEST_MEMBERS = 'REQUEST_MEMBERS';
export const RECEIVE_MEMBERS = 'RECEIVE_MEMBERS';
export const ADD_RANK = 'ADD_RANK';
export const REMOVE_RANK = 'REMOVE_RANK';
export const UPDATE_RANK = 'UPDATE_RANK';
export const ADD_MEMBER = 'ADD_MEMBER';
export const REMOVE_MEMBER = 'REMOVE_MEMBER';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const ADD_LABEL = 'ADD_LABEL';
export const REMOVE_LABEL = 'REMOVE_LABEL';
export const UPDATE_LABEL = 'UPDATE_LABEL';

// Note
export const REQUEST_NOTES = 'REQUEST_NOTES';
export const RECEIVE_NOTES = 'RECEIVE_NOTES';
export const INITIALIZE_NOTES = 'INITIALIZE_NOTES';
export const END_CREATE_NOTE = 'END_CREATE_NOTE';
export const CREATE_NOTE = 'CREATE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const ADJUST_ZOOM_LEVEL = 'ADJUST_ZOOM_LEVEL';

// User
export const INITIALIZE_USER = 'INITIALIZE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USER = 'RECEIVE_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';

// Internal
export const MODAL_PUSH = 'MODAL_PUSH';
export const MODAL_POP = 'MODAL_POP';
export const POPOUT_ADD = 'POPOUT_ADD';
export const POPOUT_REMOVE = 'POPOUT_REMOVE';
export const TOOLTIP_PUSH = 'TOOLTIP_PUSH';
export const CLEAR_TOOLTIPS = 'CLEAR_TOOLTIPS';

// Chatrooms
export const REQUEST_CHATROOMS = 'REQUEST_CHATROOMS';
export const RECEIVE_CHATROOMS = 'RECEIVE_CHATROOMS';
export const CREATE_CHATROOM = 'CREATE_CHATROOM';
export const UPDATE_CHATROOM = 'UPDATE_CHATROOM';
export const DELETE_CHATROOM = 'DELETE_CHATROOM';
export const CREATE_CHATROOM_COMMENT = 'CREATE_CHATROOM_COMMENT';
export const CREATE_LOCAL_CHATROOM_COMMENT = 'CREATE_LOCAL_CHATROOM_COMMENT';
export const REQUEST_CHATROOM_COMMENTS = 'REQUEST_CHATROOM_COMMENTS';
export const RECEIVE_CHATROOM_COMMENTS = 'RECEIVE_CHATROOM_COMMENTS';

export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';